# Generated by Django 3.0.5 on 2020-04-13 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(default='o1PCaK4XdxjFAUmi-mD_W3riiwIdUac7N0MHCNEfg_0=', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='config',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL),
        ),
    ]
