# Generated by Django 3.0.5 on 2020-04-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200413_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(default='ABAmf2daWpUbRG_Y2Ftx5bfoVDzuZqlCo2oQ8Zb7D2E=', editable=False, max_length=200),
        ),
    ]
